### ISSUE TITLE
Stop charging at X percent SoC does not work

### ISSUE THREAD

**Issue by Gnarfoz** [db-EV/ZoePHP#33]
The functionality to stop charging when the specified state of charge has been reached seems to do nothing for me.
I do get an email about reaching the threshold, and the "schedule mode" is turned on, but it just keeps on charging.
Is this supposed to work out of the box, or is there more to be done?

**Comment by db-EV** [comment]
This is a workaround which maybe not always works. Before using this function you have to define a short timer in the car when you never charge the car, for example a halv hour between 9 and 9.30. The script will activate this timer and because you are outside of the defined charging time charging will stop.

**Comment by Gnarfoz** [comment]
That makes sense. I read the OxBlog article and it seemed to imply that charging schedules could be set via the API - and then assumed that the script would do just that. I guess an explanatory notice in the README would suffice.
